import express from "express";
import cors from "cors";
import "dotenv/config";
import passport from "passport";
import adminRouter from "./routes/adminRoutes";
import authRouter from "./routes/authRoutes";
import postRouter from "./routes/postRoutes";
import "./config/passport";
const port = 8085;
const app = express();
app.use(express.json());
app.use(passport.initialize());
app.use(cors());
app.use("/admin", adminRouter);
app.use("/api/auth", authRouter);
app.use("/api/posts", postRouter);
app.listen(port, () => console.log("Server is running"));
